version: '2'

services:
    db:
        image: mysql
        # Uncomment the following lines if you want to access your mysql port externally
        # ports: 
        #     - ${MYSQL_PORT}:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: armycreator

    php7.0:
        build: php7.0-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb
        volumes:
            - "../armycreator-website:/var/www/armycreator"
            - "./logs/armycreator:/var/www/armycreator/app/logs"

    apache:
        build: apache
        ports: 
            - ${HTTP_PORT}:80
        links:
            - php7.0
        volumes_from:
            - php7.0
        volumes:
            - "./logs/apache2/:/var/log/apache2"
        environment:
            FPM_HOST: php7.0:9000

